<?php

namespace Marando\AstroCoord;

use \Marando\Units\Time;
use \Marando\Units\Angle;
use \Marando\AstroDate\AstroDate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-22 at 15:53:16.
 */
class EquatorialTest extends \PHPUnit_Framework_TestCase {

  public function testGeneric() {
    $date = AstroDate::now();
    
    $e = Equatorial::create(Time::hms(4, 6, 10.324), Angle::dms(10, 59, 8.341));
    echo "\n\n" . $e;
    echo "\n" . $b = $e->toEcliptic($date);
    echo "\n" . $b->toEquatorial($date);
    echo "\n\n";
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::create
   * @todo   Implement testCreate().
   */
  public function testCreate() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::ecliptic
   * @todo   Implement testEcliptic().
   */
  public function testEcliptic() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::horizontal
   * @todo   Implement testHorizontal().
   */
  public function testHorizontal() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::galactic
   * @todo   Implement testGalactic().
   */
  public function testGalactic() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::angles
   * @todo   Implement testAngles().
   */
  public function testAngles() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::deg
   * @todo   Implement testDeg().
   */
  public function testDeg() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::rad
   * @todo   Implement testRad().
   */
  public function testRad() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::hmsdms
   * @todo   Implement testHmsdms().
   */
  public function testHmsdms() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::toEcliptic
   * @todo   Implement testToEcliptic().
   */
  public function testToEcliptic() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::toHorizontal
   * @todo   Implement testToHorizontal().
   */
  public function testToHorizontal() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::toGalactic
   * @todo   Implement testToGalactic().
   */
  public function testToGalactic() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::celestPoleDist
   * @todo   Implement testCelestPoleDist().
   */
  public function testCelestPoleDist() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::explodeRad
   * @todo   Implement testExplodeRad().
   */
  public function testExplodeRad() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Equatorial::explodeDeg
   * @todo   Implement testExplodeDeg().
   */
  public function testExplodeDeg() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
