<?php

namespace Marando\AstroCoord;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-03 at 01:13:40.
 */
class FrameTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\AstroCoord\Frame::IRCF
   * @todo   Implement testIRCF().
   */
  public function testIRCF() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

  /**
   * @covers Marando\AstroCoord\Frame::FK5
   * @todo   Implement testFK5().
   */
  public function testFK5() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
